Nathawat12246/bun 37 login
smovidya/pussadu pull request #25
Opened 2024-02-09 06:32 UTC by bunnybunbun37204

2024-02-09 07:48 UTC, bunnybunbun37204 reviewed
that's cool but should fix layout alignment and more cleaner code plz

2024-02-09 07:48 UTC, bunnybunbun37204 commented on public/picture/yellowBox.png
it would be better idea if you make it to a svg component

2024-02-09 07:48 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
![Screenshot from 2024-02-09 14-37-54](https://github.com/smovidya/pussadu/assets/70959980/96f1786b-3ed7-4177-8ca4-f91dc4e8605b)

ลด spacing หน่อยงับ

2024-02-09 07:48 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
cleaning code; make component in component folder, more readable

2024-02-09 07:48 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
check box should be black

2024-02-09 07:48 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
or grey

2024-02-09 07:53 UTC, bunnybunbun37204 reviewed
change this file eiei

2024-02-09 07:53 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
![Screenshot from 2024-02-09 14-52-28](https://github.com/smovidya/pussadu/assets/70959980/95bc8c4c-5ea5-457a-8b9c-884aac854e7e)

button should be disabled when check box state is false

2024-02-10 04:44 UTC, OverIoad commented on src/app/login/page.tsx
when unchecking shouldn't show policy text again

2024-02-10 12:39 UTC, ratchanonp commented on public/font/Sukhumvit.css
- ทำไมถึง Self-Hosted Font เองอะ 
- Must ไหม Font นี้
- ถ้าไปใช้ Font ที่มีใน Google Fonts จะสะดวกกว่าไหมมีน้ำหนักให้เลือกเยอะกว่า https://fonts.google.com/?subset=thai&noto.script=Thai

2024-02-10 12:39 UTC, ratchanonp commented on public/picture/yellowBox.png
Agree

2024-02-10 12:41 UTC, ratchanonp commented on public/picture/yellowBox.png
Or using icon from [react-icon ](https://heroicons.com/) or  [Heroicons](https://heroicons.com/)

2024-02-10 12:43 UTC, ratchanonp commented on src/app/api/wai/condition/route.ts
> +    let { data: Item, error } = await supabase.from('Item').select("*").eq('Status', status)
Did You forget handle error?

2024-02-10 12:44 UTC, ratchanonp commented on src/app/api/wai/route.ts
> +console.log("TESTTTTTTTTT",NEXT_PUBLIC_SUPABASE_URL);
Don't forget to remove console.log in prod

2024-02-10 12:44 UTC, ratchanonp commented on src/app/api/wai/route.ts
> +  let { data: Item, error } = await supabase.from('Item').select('*');
Add Error Handler

2024-02-10 12:57 UTC, ratchanonp commented on src/app/api/wai/route.ts
> +  const req= await request.json();
Some kind of modification that will go to database must validate your data first

2024-02-10 12:59 UTC, ratchanonp commented on src/app/api/wai/route.ts
> +}
When it was deleted successfully should return some kind of 20X HTTP status, if wan't should response an error message

2024-02-10 13:04 UTC, ratchanonp commented on src/app/login/page.tsx
This is not the way you write a responsive website here is a guide https://mui.com/material-ui/guides/responsive-ui/

2024-02-10 13:06 UTC, ratchanonp commented on src/app/api/wai/route.ts
Overall
- Handle Query Error
- If you operation have to modify or insert or something you will change data you **have to** validate data before it goes to database

2024-02-10 13:12 UTC, ratchanonp requested changes
Please be consider of this thing
- You use typescript ok that is a good start but typescript is just a tool if you don't declare type strictly, typescript will not help anything at all
- Always handle you error at least throw errors to client side
- Other comment please check individual file

2024-02-10 13:55 UTC, bunnybunbun37204 commented
> Please be consider of this thing
> 
> * You use typescript ok that is a good start but typescript is just a tool if you don't declare type strictly, typescript will not help anything at all
> * Always handle you error at least throw errors to client side
> * Other comment please check individual file

Thank you for your review @OverIoad improve ur code

2024-02-12 07:16 UTC, ratchanonp commented on src/app/login/page.tsx
> +function testResponsive() {
React Components start with an uppercase letter

2024-02-12 07:19 UTC, ratchanonp commented on src/app/login/page.tsx
I forgot somethings in previous review if you use image in nextjs. I prefer use Next.js Image Components, it will help you display optimized image and it will be faster [Check this out Image Component](https://nextjs.org/docs/pages/api-reference/components/image)

2024-02-12 07:24 UTC, ratchanonp requested changes
Check this out for Optimization in Next.js
- [Image Optimization](https://nextjs.org/docs/pages/api-reference/components/image)
- [Font Optimization](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#google-fonts)

2024-02-12 12:35 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
> +                  <PolicyText></PolicyText>
It would be better if you use `<PolicyText/>` instead of `<PolicyText></PolicyText> ` it will be more readable.

2024-02-12 14:24 UTC, OverIoad commented
fix: change type of logoSmo to .svg

2024-02-12 16:31 UTC, bunnybunbun37204 reviewed
`ReferenceError: window is not defined`

2024-02-12 16:31 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
> +    window.addEventListener("resize", handleWindowSizeChange);
![image](https://github.com/smovidya/pussadu/assets/70959980/b3cc2332-1f32-4a01-a03c-e8a5bea26646)

> ReferenceError: window is not defined
>     at r5 (/home/bunyawat/Documents/my-dev/pussadu/.next/server/app/login/page.js:74:49633)
>     at nM (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47419)
>     at nN (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
>     at nI (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46806)
>     at nM (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47570)
>     at nM (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61663)
>     at nN (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64674)
>     at nB (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67657)
>     at nF (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66824)
>     at nN (/home/bunyawat/Documents/my-dev/pussadu/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64990)
> 
> Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error

When Next.js pre-renders the page, it generates the HTML then sends that to the client. When a user visits the page, it will load the HTML then rehydrate (the process of running React to allow the page to become interactive). This is where the issue can occur, and in the server side ```window``` is undefined

you have to ensure client-side code executes only when the window object is defined.

[source code can be found here](https://medium.com/@saileshadhikari72/handling-window-is-not-defined-error-in-react-and-next-js-for-client-side-code-993eec31bc48)

[source code can be found here](https://blog.sethcorker.com/question/how-to-solve-referenceerror-next-js-window-is-not-defined/)

Is there a better way and best practice kub @ratchanonp

2024-02-13 04:47 UTC, ratchanonp commented on src/app/login/page.tsx
> +    window.addEventListener("resize", handleWindowSizeChange);
Check window is not undefined is deprecated way to fix it. I prefer call the thing you want to execute in client side in useEffect hook

2024-02-13 04:52 UTC, ratchanonp commented on src/app/login/page.tsx
> +    window.addEventListener("resize", handleWindowSizeChange);
But if you still face with an error you can use condition to check windows is not undefined

2024-02-13 14:39 UTC, bunnybunbun37204 commented on src/app/login/page.tsx
> +    window.addEventListener("resize", handleWindowSizeChange);
call it in useEffect is work thank you kub

2024-02-13 14:41 UTC, merged